app/models.py
# from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin
from datetime import datetime

from . import db, login_manager

@login_manager.user_loader
def login_user(user_id):
    return User.query.get(int(user_id))


# Users
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image = db.Column(db.String(120), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author',lazy=True) #defining the one to many relationship btn post and author
    comment = db.relationship('Comment', backref='user', lazy='dynamic')
    likes =  db.relationship('Like',backref='user',lazy='dynamic')


def __repr__(self):
    return f'User({self.username}, {self.email},{self.image})'

class Post (db.Model):

    id = db.Column(db.Integer, primary_key=True)
    datePosted = db.Column(db.DateTime, nullable=False,default=datetime.utcnow)
    title = db.Column(db.Text, nullable=False)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False) #Id of the post author
    comment =  db.relationship('Comment',backref='post',lazy='dynamic')
    likes =  db.relationship('Like',backref='post',lazy='dynamic')




def __repr__(self):
    return f"User({self.content},{self.datePosted})"

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False) #Id of the user
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'),nullable=False)
    comment = db.Column(db.String(100))




def __repr__(self):
    return f'User({self.comment})'


class Like(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False) #Id of the user
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'),nullable=False)
   
# Quotes fetched from the api
class Quote:
    def __init__(self, author, quote):
        self.author = author
        self.quote = quote

# class Subscription(db.Model):
#     id = db.Column(db.Integer, primary_key = True)
#     email = db.Column(db.String(255), unique = True, index = True)

#     def save_subscriber(self):
#         db.session.add(self)
#         db.session.commit()

#     def __repr__(self):
#         return f'Subscriber {self.email}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,StringField,PasswordField, SubmitField, BooleanField
from wtforms.validators  import DataRequired, ValidationError
from flask_login import current_user




class PostForm(FlaskForm):
    
    title = StringField('Post Title',validators=[DataRequired()])

    content = TextAreaField('Post Content',validators=[DataRequired()])

    submit = SubmitField('Publish Post')

class CommentForm(FlaskForm):
    comment = StringField('Comment')
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_mail import Mail
from flask_bootstrap import Bootstrap



from config import config_options


# Initializing extensions:
db = SQLAlchemy()
bcrypt = Bcrypt()
mail = Mail()
bootstrap = Bootstrap()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
login_manager.login_message_category='info'

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)



    # Will add the views and forms
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # create login view function
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms

app/main/views.py
from webbrowser import get
from flask import render_template,request,redirect,url_for
from flask import abort,request,redirect, render_template, url_for,flash
from flask_login import login_required,current_user

from .forms import PostForm,CommentForm
from . import main
from ..models import Post, User, Like, Comment, Quote
from .. import db
from ..requests import getRandorm #getPopular


# Views
@main.route('/')
def home():
    randormQuote = getRandorm()

    return render_template('index.html', randormQuote=randormQuote)


# @main.route('/quotes')
# def quotes():

#     # popularQuote =  getPopular()   
#     return render_template('quotes.html')



@main.route('/all/posts')
def blog():
    posts = Post.query.all()

    return render_template('blog.html', posts=posts)

@main.route('/contact')
def contact():
    name = "Time to get started"
    
    return render_template('contact.html', name=name)



@main.route('/post/new',methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    if form.validate_on_submit():
        post=Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post published successfully!','success')
        return redirect(url_for('main.blog'))
    return render_template("post.html", form=form)


@main.route('/like/<post_id>/',methods = ['GET'])
@login_required
def like(post_id):
    post = Post.query.filter_by(id=post_id)
    like = Like.query.filter_by(author= current_user.id, post_id=post_id).first()

    if not post:
        flash('Post not found',category='error')
    elif like:
        return redirect(url_for('main.home', post_id=post_id))
    else:
        like= Like(author=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()

    return redirect(url_for('main.blog'))

@main.route('/comment/<int:post_id>',methods = ['POST','GET'])
@login_required
def comment(post_id):
    post=Post.query.get_or_404(post_id)
    form = CommentForm()
    allComments = Comment.query.filter_by(post_id = post_id).all()
    if form.validate_on_submit():
        postedComment = Comment(comment=form.comment.data,user_id = current_user.id, post_id = post_id)
        post_id = post_id
        db.session.add(postedComment)
        db.session.commit()
        flash('Comment added successfully')
        
        return redirect(url_for('main.comment',post_id=post_id))

    return render_template("comment.html",post=post, title='React to post!', form = form,allComments=allComments)

# Delete comment
@main.route('/delete/comment/<comment_id>')
@login_required

def deleteComment(comment_id):
    comment = Comment.query.filter(Comment.id == comment_id).first()

    db.session.delete(comment)
    db.session.commit()
    flash('Your comment has been deleted!', 'success')
    return redirect(url_for('main.blog'))



@main.route('/delete/post/<int:post_id>',methods=['POST'])
@login_required
def deletePost(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted!', 'success')
    return redirect(url_for('main.post'))



@main.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def updatePost(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post has been updated!', 'success')
        return redirect(url_for('main.blog', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('post.html', title='Update Post',
                           form=form, legend='Update Post')

# @main.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
# @login_required
# def subscribe

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!--Custom CSS-->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base.css') }}">
  <title>Noor's Blog</title>
</head>

<body class="">
  <div class="container-fluid">
    <!-- <div class="mr-auto"style="">
      <small class="text-muted">Talk to us: 0743068355</small>
    </div>
    <div class="">
      <small class="text-muted ">Write to us: info@blog.volutions</small>
    </div> -->
  <div class="container-fluid text-center">
   
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
     
      <div class="container mt-4 mb-2" style="background-color:#000;">
        <a class="navbar-brand mr-4" href="/"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('main.blog') }}">Posts</a>

          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav ms-auto">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link align-right" style="color: #DB8CF6; font-weight: bold"
              href="{{ url_for('main.post') }}">New Post</a>
            <a class="nav-item nav-link align-right" href="{{ url_for('auth.account') }}">
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#DB8CF6" class="bi bi-person-circle"
                viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                <path fill-rule="evenodd"
                  d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
              </svg>
            </a>
            <a class="nav-item nav-link align-right" href="{{ url_for('auth.logout') }}">
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#DB8CF6"
                class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                  d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                <path fill-rule="evenodd"
                  d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
              </svg>
            </a>
            <!-- <a class="nav-item nav-link align-right" href="{{ url_for('main.contact') }}" style="color:#fff">Get In Touch </a> -->
            {% else%}

            <a class="nav-item nav-link align-right" href="{{ url_for('auth.login') }}">
              Login
            </a>
            <a class="nav-item nav-link align-right" href="{{ url_for('auth.register') }}">
              Get Started
            </a>
            <!-- <a class="nav-item nav-link align-right" href="{{ url_for('main.contact') }}">Get In Touch </a> -->

            {% endif %}

          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <img src="{{ url_for('static', filename='logo.png') }}" style="width: 40%; height:35%; padding-top:1em; padding-bottom: 0.5em;"/>
    </div>
   </div>
  <main role="main" class="container-fluid">
    {% block content %}{% endblock %}
  </main>
</div>
  <!--jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
</body>

</html>

app/templates/blog.html
{% extends 'base.html' %}
<!-- Content block -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% for post in posts %}
            <article class="media content-section"  style="border:none;box-shadow: rgba(100, 100, 110, 0.2) 0px 8px 8px;border-radius: 5px;">
                <img class="rounded-circle" article-img
                src="{{ url_for('static', filename='default.jpg.png' + post.author.image) }}">
                <div class="media-body">
                  <div class="article-metadata">
                    <a class="mr-2" style="color:#000">{{ post.author.username }}</a>
                    <small class="text-muted"><span style="color: #DB8CF6"> {{ post.datePosted.strftime('%Y-%m-%d') }} </span></small>
                  </div>
                  <h2><a class="article-title" href="{{ url_for('main.post', post_id=post.id) }}" style="font-size:20px;">{{ post.title }}</a></h2>
                  <p class="article-content">{{ post.content }}</p>
                <br/>
                    <a class="ms-5 mr-5" style="text-decoration: none;" href="{{ url_for('main.like', post_id=post.id) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#DB8CF6"
                            class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                            <path
                                d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z" />
                        </svg>
                        <span style="color:#000"> {{ post.likes.count()}} </span>
                    </a>
                                                                                                         
                    <a class="ms-5 mr-5" style="text-decoration: none;"
                        href="{{ url_for('main.comment', post_id=post.id) }}">

                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#DB8CF6" class="bi bi-chat"
                            viewBox="0 0 16 16">
                            <path
                                d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z" />
                        </svg>
                        <span style="color:#000"> {{post.comment.count()}} </span>
                    </a>
                    {% if current_user.id == post.author.id %}
                    <a class="ms-5 mr-5"
                    style="text-decoration: none"
                        href="{{ url_for('main.updatePost', post_id=post.id) }}"
                    >
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#DB8CF6" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                    </svg>
                    </a>
                            <a class="ms-5 mr-5"
                      style="text-decoration: none"
                      href="{{ url_for('main.deletePost', post_id=post.id) }}"
                    >
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        fill="#DB8CF6"
                        class="bi bi-trash3-fill"
                        viewBox="0 0 16 16"
                      >
                        <path
                          d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"
                        />
                      </svg>
                    </a>

                    {% endif %}

                </div>
            </article>
            {% endfor %}
        </div>
        <!--SIDE BAR-->
        <div class="col-md-4" style="height:700px;background: #FFFFFF;box-shadow: 0px 4px 4px rgba(219, 140, 246, 0.3);border-radius: 20px; margin-bottom: 2em; margin-top: 1em;">
            <div class="content-section mb-2 mt-1" style="height: 420px; background: rgba(219, 140, 246, 0.12);border-radius:15px">
                <h3 class="text-center" style="font-family: Inika;">Hello Visitor!</h3>
                <p class='text-muted'>
                    <div class="card-image">
                    <img src="{{ url_for('static', filename='read.png') }}" style="width: 100%; height:80%" />
                    </div>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light"><a style="text-decoration:none; color:#DB8CF6"  href="{{ url_for('main.blog') }}">View All Posts</a></li>
                    <li class="list-group-item list-group-item-light"><a style="text-decoration:none; color:#DB8CF6"  href="{{ url_for('auth.login') }}">New Post</a></li>
                    <li class="list-group-item list-group-item-light"><a style="text-decoration:none; color:#DB8CF6"  href="{{ url_for('auth.register') }}">Get Started</a></li>
                    <!-- <li class="list-group-item list-group-item-light"><a style="text-decoration:none; color:#DB8CF6"  href="{{ url_for('main.contact') }}">Get In Touch</a></li> -->
                </ul>
                </p>
            </div>
            <div class="content-section mb-2 mt-1" style="height: 260px; background: rgba(219, 140, 246, 0.12); border-radius: 15px;">
                <h3 class="text-center" style="font-family: Inika;">Join Our Mailing List</h3>
                <div class="col-md-4">
    
                    <form class="form-inline ml-2" action="{{url_for('main.post')}}" method="POST" style="margin-bottom: 20px">
                      <div class="md-form form-group">
                        <!-- <label class="white-color">Email Address...</label><br> -->
                        <input type="email" class="form-control " name="subscriber" required>
                      </div> 
                      <br/>
                      <button class="center button-17" href="#">Join</button>
                      <div class="md-form form-group">
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

app/templates/comment.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row">
    <div
      class="col-md-8"
      style="
        border: none;
        box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
        border-radius: 5px;
      "
    >
      <article class="media content-section">
        <img
          class="rounded-circle"
          article-img
          src="{{ url_for('static', filename='default.jpg.png/' + post.author.image) }}"
        />
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2">{{ post.author.username }}</a>
            <small class="text-muted"
              ><span style="color: #db8cf6">
                {{ post.datePosted.strftime('%Y-%m-%d') }}
              </span></small
            >
          </div>
          <h2>
            <a
              class="article-title"
              href="{{ url_for('main.post', post_id=post.id) }}"
              >{{ post.title }}</a
            >
          </h2>
          <p class="article-content">{{ post.content }}</p>
          <br />
          <a
            class="ms-5 mr-5"
            style="text-decoration: none"
            href="{{ url_for('main.like', post_id=post.id) }}"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              fill="#DB8CF6"
              class="bi bi-suit-heart-fill"
              viewBox="0 0 16 16"
            >
              <path
                d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"
              />
            </svg>
            <span style="color: #000"> {{ post.likes.count()}} </span>
          </a>

          <a
            class="ms-5 mr-5"
            style="text-decoration: none"
            href="{{ url_for('main.comment', post_id=post.id) }}"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              fill="#DB8CF6"
              class="bi bi-chat"
              viewBox="0 0 16 16"
            >
              <path
                d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"
              />
            </svg>
            <span style="color: #000"> {{post.comment.count()}} </span>
          </a>
        </div>
      </article>
      <!--Display Commentr-->
      {% for comment in allComments %}
      <div class="row">
        <div class="col">
          <ul>
            <li style="width: auto; list-style-type: none">
              <span
                >{{ comment.comment }} by
                <small class="text-muted">{{comment.user.username}}</small>
              </span>
            </li>
          </ul>
        </div>
        <div class="col">
          {% if current_user.id == comment.user.id or current_user.id ==
          post.author.id %}
          <a
            style="text-decoration: none"
            href="{{ url_for('main.deleteComment', comment_id=comment.id) }}"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="#fea150"
              class="bi bi-trash3-fill"
              viewBox="0 0 16 16"
            >
              <path
                d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"
              />
            </svg>
          </a>
          {% endif %}
        </div>
        </div>
        {% endfor %}
        <!--COMMENT FORM-->
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <div class="row border-top">
            <div class="col">
              <fieldset class="form-group">
                <div class="form-group mb-2">
                  {{ form.comment.label(class="form-control-label") }} {% if
                  form.comment.errors %} {{ form.comment(class="form-control
                  form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.comment.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% else %} {{ form.comment(class="form-control
                  form-control-lg") }} {% endif %}
                </div>
              </fieldset>
            </div>
            <div class="col">
              <div class="form-group mt-4 mb-4">
                {{ form.submit(class="btn btn-outline-info button-17") }}
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endblock content %}
</div>

app/templates/contact.html
{% extends 'base.html' %}


<!-- Content block -->
{% block content %}

<h1>Noor's Blog</h1>

{% endblock%}

app/templates/quotes.html
{% extends 'base.html' %}


<!-- Content block -->
{% block content %}
{% for popularQuote in popularQuote %}

<div class="col-sm-12">
    <div class="cards">
        <div class="card">
            <div class="card-body" >
            <blockquote class="blockquote mb-0 card-body">
                <p>{{popularQuote.quote}}</p>
                <footer class="blockquote-footer">
                    <cite title="Source Title" style="color: black;" >{{popularQuote.author| capitalize}}</cite>
                    
                </footer>
                
              </blockquote>
            </div>
            

    </div>
</div>

{% endfor %}

{% endblock%}

app/templates/subscription.html
{% extends 'base.html'%}
{%block content%}
<div class="col-md-4">
    
    <form class="form-inline ml-2" action="{{url_for('main.subscribe')}}" method="POST" style="margin-bottom: 20px">
      <div class="md-form form-group">
        <label class="white-color">Email Address...</label><br>
        <input type="email" class="form-control " name="subscriber" required>
      </div><br><br>
      <div class="md-form form-group">
        <button class="btn btn-info" id="subs">Subscribe</button>
      </div>
    </form>
</div>
{%endblock%}